### ISSUE TITLE
How should it work on GTZAN dataset?

### ISSUE THREAD

**Issue by AmberLau** [jsalbert/music-genre-classification#1]
I fill the music folder with the dataset & write filenames in list_example.txt, after I run the program I got an error which is:
Traceback (most recent call last):
  File "quick_test.py", line 47, in <module>
    X_test, num_frames_test= extract_melgrams(test_songs_list, MULTIFRAMES, process_all_song=False, num_songs_genre='')
  File "/home/lauyick/Workspaces/python/DLR-DQN/utils.py", line 124, in extract_melgrams
    melgrams = np.concatenate((melgrams, melgram), axis=0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
It seems that something wrong with the array size when using numpy.

**Comment by AmberLau** [comment]
maybe i've fixed it, sry!

**Comment by jsalbert** [comment]
I have added the lists containing the name of the GTZAN dataset, if you change the paths to your dataset it should work.
If you want to test it using GTZAN I suggest using the script [train_tagger_net.py](https://github.com/jsalbert/Music-Genre-Classification-with-Deep-Learning/blob/master/train_tagger_net.py) and putting the paths of the song list while setting TEST mode.

**Comment by AmberLau** [comment]
Thanks a lot!
Have you try it with Million Song Dataset or its subset?

**Comment by jsalbert** [comment]
No, we trained with a custom dataset and tested on gtzan. I think we had 300 songs in total, 30 per genre.

**Comment by AmberLau** [comment]
Do I need to change other parameters while using train_tagger_net.py ?I've changed the paths to my dataset & also got an error like I posted in the issue. I tried to set process_all_song in to True but it didn't work...

**Comment by jsalbert** [comment]
@AmberLau this is an old project and we are currently don't working on it, but I suggest you look at [here](https://github.com/keunwoochoi/music-auto_tagging-keras) to see the models and maybe you could take our train code as example.
